services:
  pg:
    image: postgres:15.3-alpine
    container_name: revuehub-api-pg
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 1s
      timeout: 2s
      retries: 5
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revuehub
    ports:
      - 5432:5432
  redis:
    image: redis:6.2-alpine
    container_name: revuehub-api-redis
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 2s
      retries: 5
    ports:
      - 6379:6379
  app:
    build:
      context: .
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      [
        '/bin/sh',
        '-c',
        'yarn migrate:latest --env production && yarn start:prod',
      ]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@revuehub-api-pg:5432/revuehub
      REDIS_URL: redis://revuehub-api-redis:6379
      PORT: 1001
    ports:
      - 1001:1001
